import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { NavMenu } from "@/components/nav-menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next.js Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { slug: string };
}>) {
  console.log(params.slug);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavMenu />
        <div className="min-h-screen w-full flex flex-col items-center justify-center max-w-3xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
